title: Software Developer
author: Iván Aspíllaga
email: ivan.aspillaga@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Code samples; Personal projects; Fun code

# social links
twitter_username: ivantz_ # DO NOT include the @ character, or else the build will fail!
github_username:  ivanaspillaga # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
